apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# zot in-cluster OCI registry, in the golden-images namespace (created by the cdi catalog component).
namespace: golden-images
resources:
  - zot.yaml
